config/routes.rb
JustNotes::Application.routes.draw do

  get 'users/:id/page/:page', to: 'users#show'

  resources :users do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag1       :string(255)
#  tag2       :string(255)
#  tag3       :string(255)
#

class Note < ActiveRecord::Base
  attr_accessible :content, :title, :tag1, :tag2, :tag3
  belongs_to :user

  validates :content, presence: true
  validates :user, presence: true
  validates :user_id, presence: true

  default_scope order: 'notes.updated_at DESC'

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: :destroy

  respond_to :html, :js, :json

  # cache_sweeper :note_sweeper

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.new(params[:note])
    if @note.save
      flash[:notice] = "Note successfully created."
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(params[:note])
    if @note.save
      flash[:notice] = "Note successfully updated."
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id], include: :user)
    @user = @note.user
    @note.destroy
  end

  def index
    title_param = params[:q]
    user_id_param = params[:user_id]
    notes = Note.select{[id, title.as("name")]}.where{title.matches("%#{title_param}%") & user_id.eq("#{user_id_param}")}
    respond_with(notes)
  end

  private

    def correct_user
      @note = current_user.notes.find_by_id(params[:id])
      redirect_to root_path if @note.nil?
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note, validate: true, url: url_path, html: {class: "form-vertical note"}) do |f| %>

  <%= f.input :title, input_html: { class: "input-xlarge" } %>

  <%= f.input :tags, label: "Tags" do %>
    <%= f.input_field :tag1, class: "input-small" %>
    <%= f.input_field :tag2, class: "input-small" %>
    <%= f.input_field :tag3, class: "input-small" %>
  <% end %>

  <%= f.input :content, input_html: { class: "redactor span7" } %>

  <div class="form-actions">
	  <%= f.button :submit, class: 'btn btn-primary' %>
	  <%= link_to 'Cancel', root_path, class: "btn",
	      confirm: "Are you sure that you don't want to save this Note?" %>
  </div>

<% end %>

app/views/notes/_note_row.html.erb
<% note_link = edit_user_note_path(@user, note) %>
<tr id='note_row_id<%= note.id %>'>
  <td class="delete_icon">
    <%= link_to "", user_note_path(@user, note), method: :delete, class: 'icon-minus-sign', title: 'Delete Note', remote: true,
        confirm: "Are you sure that you want to delete Note ##{note.id}?" %>
  </td>
  <td class="hand_pointer" data-link="<%= note_link %>">
    <%= note.id %>
  </td>
  <td class="hand_pointer" data-link="<%= note_link %>">
    <%= note.title %>
  </td>
  <td class="hand_pointer" data-link="<%= note_link %>">
    <div class="">
      <div class="more-block">
        <p><%= sanitize note.content %></p>
      </div>
    </div>
  </td>
  <td class="hand_pointer" data-link="<%= note_link %>">
    <%= timeago(note.created_at) %>
  </td>
  <td class="hand_pointer" data-link="<%= note_link %>">
   <%= timeago(note.updated_at) %>
  </td>
 <tr>

app/views/notes/_notes_table.html.erb
<div id="notes_table">
  <table class="table">
    <thread>
      <th class="delete_icon_header"></th>
      <th>#</th>
      <th>Title</th>
      <th>Content</th>
      <th>Created</th>
      <th>Updated</th>
    </thread>
      <tbody class="notes_table_body">
        <%= render partial: 'notes/note_row', collection: @notes, as: 'note' %>
      </tbody>
  </table>
  <div class="center">
    <%= will_paginate @notes, params: {controller: 'users', action: 'show', id: @user.id} %>
  </div>
</div>

app/views/notes/destroy.js.erb
$("#note_row_id<%= @note.id %>").hide('slow')
$("#total_notes").html("<%= escape_javascript(pluralize(@user.notes.count, 'Note')) %>.")

app/views/notes/edit.html.erb
<%= provide(:title, 'Edit Note') %>

<div class="row">
  <div class="span7 offset3">

    <legend>Edit Note</legend>

    <%= render partial: 'form', locals: {url_path: user_note_path} %>

  </div>
</div>

app/views/notes/new.html.erb
<%= provide(:title, 'New Note') %>

<div class="row">
  <div class="span7 offset3">

    <legend>New Note</legend>

    <%= render partial: 'form', locals: {url_path: user_notes_path} %>

  </div>
</div>