config/routes.rb
JustNotes::Application.routes.draw do

  get 'users/:id/page/:page', to: 'users#show'

  resources :users do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :email, presence: true
  validates :password, length: { minimum: 6 }, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_many :notes, dependent: :destroy
  has_and_belongs_to_many :roles, uniq: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :notes, :show]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @notes = @user.notes.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:notice] = "Welcome to Just Notes!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User destroyed"
    redirect_to users_path
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(note, url: user_notes_path, html: {class: "form-vertical"}) do |f| %>
  
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :title %>
  <%= f.input :content %>

  <div class="form-actions">
  <%= f.button :submit, :class: 'btn btn-large btn-primary' %>
  <%= link_to 'Cancel', root_path, class: "btn btn-large btn-danger",
      confirm: "Are you sure that you don't want to save this Note?" %>
  </div>

<% end %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<div class="row">
  <div class="span6 offset3">
    <%= simple_form_for(@user, html: {class: "form-horizontal"}) do |f| %>
      <legend>Sign Up</legend>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.input :name %>

      <%= f.input :email, placeholder: 'user@domain.com' %>

      <%= f.input :password %>

      <%= f.input :password_confirmation, :label => "Confirmation" %>

      <div class="form-actions">
        <%= f.button :submit, 'Sign Up', :class => 'btn btn-large btn-primary' %>
        <%= link_to 'Cancel', root_path, class: "btn btn-large btn-danger" %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row-fluid">
  <div class="span12">
    <h3>
      Hi, <%= @user.name %>!
        You have a total of
        <span id="total_notes">
          <%= pluralize(@user.notes.count, 'Note') %>.
        </span>
        <input type="text" id="searchTitles" placeholder="Search Titles">
        <div class="pull-right">
          <span id="btn_edit_notes" title="Edit Notes" class="btn">
            <i class="icon-pencil"></i><span id="btn_edit_notes_text"> Edit</span>
          </span>
          <span>
            <%= link_to(new_user_note_path(@user) , class: "btn btn-success", title: "Create a new Note") do %>
              <i class="icon-plus icon-white"></i> New Note
            <% end %>
          </span>
        </div>
    </h3>
    </br>
      <% if @user.notes.any? %>
        <%= render 'notes/notes_table' %>
      <% end %>
  </div>
</div>

app/views/users/show.js.erb
$("<%= j render partial: 'notes/note_row', collection: @notes, as: 'note' %>").appendTo('.notes_table_body');
<% if @notes.next_page %>
	$('.pagination').replaceWith("<%= j will_paginate @notes, params: {controller: 'users', action: 'show', id: @user.id} %>");
<% else %>
	$('.pagination').remove();
<% end %>
// call all of the relevant functions that are in users.js.erb
moreLess();
clickableRows();
hideDeleteIcons();
$("abbr.timeago").timeago();